In [ ]:
# Method A
# Good article https://dev.to/aspittel/how-i-finally-wrote-a-sudoku-solver-177g

import sys
print(sys.path)

import numpy as np  

#Numpy version:  1.25.2
print("Numpy version: ", np.__version__)

In [ ]:
# Her giver vi de faste tal
#---------------------------

sudoku_wrong = np.array([[0, 0, 0, 7, 0, 0, 0, 0, 0],
[8, 1, 0, 0, 0, 1, 0, 9, 0],
[0, 0, 0, 0, 9, 5, 0, 0, 7],
[0, 0, 7, 1, 0, 0, 0, 0, 6],
[0, 3, 9, 0, 0, 0, 2, 8, 0],
[2, 0, 0, 0, 0, 9, 1, 0, 0],
[4, 0, 0, 6, 1, 0, 0, 0, 0],
[0, 2, 0, 1, 0, 0, 0, 6, 1],
[0, 0, 0, 0, 0, 2, 0, 0, 0]])

# sudoku_0 = np.array( [4., 0., 0. 0. 8. 0. 0. 0. 0.],
#  [0. 3. 0. 0. 0. 0. 0. 8. 7.],
#  [0. 0. 7. 0. 3. 1. 5. 0. 0.],
#  [3. 0. 0. 0. 0. 6. 0. 0. 0.],
#  [0. 5. 1. 0. 9. 0. 2. 6. 0.],
#  [0. 0. 0. 5. 0. 0. 0. 0. 4.],
#  [0. 0. 8. 6. 1. 0. 4. 0. 0.],
#  [2. 9. 0. 0. 0. 0. 0. 1. 0.],
#  [0. 0. 0. 0. 5. 0. 0. 0. 9.] )

# bog side 14
sudoku_1 = np.array([
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0 ],  # zero betyder tom plads
               [ 4, 0, 9, 7, 0, 2, 1, 0, 3 ], 
               [ 2, 0, 3, 4, 0, 9, 7, 0, 6 ],
               [ 0, 4, 0, 0, 0, 0, 0, 9, 0 ],
               [ 8, 0, 2, 0, 0, 0, 4, 0, 5 ],
               [ 0, 3, 0, 0, 0, 0, 0, 1, 0 ],
               [ 1, 0, 7, 3, 0, 4, 5, 0, 8 ],
               [ 6, 0, 8, 2, 0, 1, 3, 0, 9 ],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0 ] 
                    ])
print(" shape = {} \n sudoku_1 = \n {}".format(sudoku_1.shape, sudoku_1))

#book page 6 
sudoku_2 = np.array([
               [ 0, 0, 2, 0, 0, 0, 6, 0, 0 ],  # zero betyder tom plads
               [ 5, 0, 0, 7, 0, 6, 0, 0, 8 ],
               [ 0, 4, 8, 0, 0, 0, 5, 7, 0 ],
               [ 1, 0, 0, 8, 6, 2, 0, 0, 7 ],
               [ 0, 0, 6, 4, 0, 1, 8, 0, 0 ],
               [ 7, 0, 0, 9, 5, 3, 0, 0, 1 ],
               [ 0, 6, 3, 0, 0, 0, 7, 9, 0 ],
               [ 4, 0, 0, 2, 0, 8, 0, 0, 6 ],
               [ 0, 0, 9, 0, 0, 0, 4, 0, 0 ]
                    ])
print(" shape = {} \n sudoku_2 = \n {}".format(sudoku_2.shape, sudoku_2))


sudoku_3 = np.array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
          [6, 0, 0, 1, 9, 5, 0, 0, 0],
          [0, 9, 8, 0, 0, 0, 0, 6, 0],
          [8, 0, 0, 0, 6, 0, 0, 0, 3],
          [4, 0, 0, 8, 0, 3, 0, 0, 1],
          [7, 0, 0, 0, 2, 0, 0, 0, 6],
          [0, 6, 0, 0, 0, 0, 2, 8, 0],
          [0, 0, 0, 4, 1, 9, 0, 0, 5],
          [0, 0, 0, 0, 8, 0, 0, 7, 9]] )

sudoku_4 = np.array([
          [0, 0, 4, 0, 0, 0, 0, 8, 9],
          [6, 3, 0, 0, 0, 5, 0, 1, 0],
          [0, 0, 7, 0, 0, 6, 0, 0, 5],
          [7, 0, 0, 9, 0, 0, 0, 0, 2],
          [0, 0, 2, 7, 0, 4, 0, 5, 0],
          [0, 4, 0, 8, 0, 3, 0, 0, 0],
          [2, 0, 0, 5, 0, 0, 0, 9, 0],
          [0, 0, 0, 3, 0, 0, 0, 4, 0],
          [0, 0, 3, 0, 0, 9, 0, 0, 0]] )

# book page 102
sudoku_5 = np.array([
          [0, 0, 0, 0, 3, 4, 9, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 2, 0, 8, 9, 0, 4, 7],
          [0, 0, 9, 0, 0, 0, 1, 0, 4],
          [4, 7, 0, 0, 0, 0, 0, 9, 6],
          [2, 0, 5, 0, 0, 0, 7, 0, 0],
          [8, 9, 0, 1, 7, 0, 5, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 7, 9, 5, 0, 0, 0, 0]] )

# fjends folkeblad uge 22
sudoku_6 = np.array([
          [4, 0, 7, 0, 8, 0, 0, 0, 0],
          [0, 5, 0, 0, 0, 0, 0, 2, 6],
          [0, 3, 2, 0, 0, 0, 0, 0, 0],
          [8, 9, 0, 4, 0, 0, 0, 0, 0],
          [2, 0, 0, 0, 0, 0, 0, 6, 7],
          [0, 0, 6, 0, 0, 0, 0, 0, 4],
          [3, 0, 0, 6, 0, 1, 0, 0, 0],
          [1, 0, 9, 0, 4, 0, 2, 0, 8],
          [0, 0, 0, 3, 0, 0, 0, 0, 0]] )

# skive folkeblad uge 23, Sudoku 1
sudoku_7 = np.array([
          [0, 1, 0, 0, 0, 0, 0, 0, 2],
          [0, 0, 0, 1, 0, 0, 8, 0, 0],
          [7, 8, 0, 0, 4, 6, 1, 3, 0],
          [0, 9, 0, 6, 0, 3, 0, 0, 0],
          [0, 0, 1, 0, 0, 0, 5, 0, 0],
          [5, 7, 0, 0, 0, 0, 3, 0, 0],
          [0, 6, 0, 5, 3, 0, 2, 7, 0],
          [0, 0, 0, 4, 0, 8, 0, 0, 0],
          [0, 0, 8, 0, 0, 0, 0, 0, 5]] )

# Skive Folkeblad uge 25 
sudoku_8 = np.array([
          [0, 0, 0, 0, 7, 0, 0, 0, 4],
          [0, 3, 0, 0, 1, 0, 0, 7, 0],
          [0, 0, 0, 0, 0, 0, 9, 0, 6],
          [0, 8, 9, 0, 3, 2, 0, 0, 0],
          [0, 0, 7, 0, 0, 8, 0, 3, 0],
          [0, 0, 0, 7, 0, 0, 5, 0, 0],
          [4, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 7, 0, 3, 5, 0, 0, 8, 0],
          [5, 0, 0, 0, 8, 0, 0, 9, 1] ])
           
                       
# Wikipedia hard for brute force 
sudoku_9 = np.array([
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 3, 0, 8, 5],
          [0, 0, 1, 0, 2, 0, 0, 0, 0],
          [0, 0, 0, 5, 0, 7, 0, 0, 0],
          [0, 0, 4, 0, 0, 0, 1, 0, 0],
          [0, 9, 0, 0, 0, 0, 0, 0, 0],
          [5, 0, 0, 0, 0, 0, 0, 7, 3],
          [0, 0, 2, 0, 1, 0, 0, 0, 0],
          [0, 0, 0, 0, 4, 0, 0, 0, 9] ])
                                  

In [ ]:
# DET ER EN VIGTIG TEST 
# Det skal være tydeligt hvordan man håndtere
# parameter i funktioner

x1 = np.array([0,1,2,3,4])
print("{} // Første x1".format(x1))

def func1(a,x):
    print("{} // x i funktionen før append".format(x))
    x = np.append(x,a)
    print("{} // x i funktionen efter append".format(x))

func1(2,x1)
print("{} // x1 efter funktionen".format(x1))


In [ ]:
# Test np.isin() functionen
x1 = np.array([ 0,1,2,3,4,4,8,0,1,2])
print(np.isin(x1,[8,1]))
print(np.sum(np.isin(x1,8)))

In [ ]:
def er_der_tal_i_linjen(k,i,sudoku_fast):
    for kk in sudoku_fast[i,:]:
        if ( kk == k ):
             return 1  
    return 0

# Tester 
sudoku_fast_test = sudoku_1 
print(er_der_tal_i_linjen(1,7,sudoku_fast_test)) # Resultat 1 
print(er_der_tal_i_linjen(7,7,sudoku_fast_test)) # Resultat 0
print(er_der_tal_i_linjen(1,6,sudoku_fast_test)) # Resultat 1

In [ ]:
def er_der_tal_i_soejlen(k,j,sudoku_fast):
    for kk in sudoku_fast[:,j]:
        if ( kk == k ):
             return 1  
    return 0

# Tester 
sudoku_fast_test = sudoku_1 
print(er_der_tal_i_soejlen(4,1,sudoku_fast_test)) # Resultat 1
print(er_der_tal_i_soejlen(8,1,sudoku_fast_test)) # Resultat 0
print(er_der_tal_i_soejlen(8,2,sudoku_fast_test)) # Resultat 1

In [ ]:
def er_der_tal_i_kvadraten(k,i,j,sudoku_fast):
    
    ii = int(np.floor(i/3)*3)
    jj = int(np.floor(j/3)*3)
    
    tal_i_kvadrat = np.reshape(sudoku_fast[ii:ii+3,jj:jj+3],[9])
    
    for kk in tal_i_kvadrat:
        if ( kk == k ):
            return 1 
    
    return 0

# Tester
sudoku_fast_test = sudoku_1  
print(er_der_tal_i_kvadraten(2,3,2,sudoku_fast_test)) # 1
print(er_der_tal_i_kvadraten(2,3,2,sudoku_fast_test)) # 1
print(er_der_tal_i_kvadraten(8,3,2,sudoku_fast_test)) # 1
print(er_der_tal_i_kvadraten(4,3,2,sudoku_fast_test)) # 1
print(er_der_tal_i_kvadraten(9,3,2,sudoku_fast_test)) # 0
print(er_der_tal_i_kvadraten(9,7,7,sudoku_fast_test)) # 1
print(er_der_tal_i_kvadraten(4,7,7,sudoku_fast_test)) # 0

In [ ]:
def kan_k_vaere_her(k,i,j,sudoku_fast):
    
    # extra sikkerhed 
    if (sudoku_fast[i,j]!=0):
        return 0
        
    if (er_der_tal_i_kvadraten(k,i,j,sudoku_fast)):
        return 0
    
    if er_der_tal_i_soejlen(k,j,sudoku_fast):
        return 0
    
    if er_der_tal_i_linjen(k,i,sudoku_fast):
        return 0
    
    return 1

# Tester
sudoku_fast_test = sudoku_1
print(kan_k_vaere_her(2,3,2,sudoku_fast_test)) # 0 
print(kan_k_vaere_her(9,3,2,sudoku_fast_test)) # 0 
print(kan_k_vaere_her(1,3,2,sudoku_fast_test)) # 1
print(kan_k_vaere_her(1,3,1,sudoku_fast_test)) # 0

In [ ]:
def hvad_kan_vaere_her(i,j,sudoku_fast):
    
    kasse_muligheder = np.zeros(9)
    
    idx = 0
    for k in np.arange(1,10):
        # hvis den ikke kan være her, 
        if ( kan_k_vaere_her(k,i,j,sudoku_fast) == 1 ):
            kasse_muligheder[idx] = k
            idx = idx + 1

    return kasse_muligheder

# Tester
sudoku_fast_test = sudoku_1
print(hvad_kan_vaere_her(0,0,sudoku_fast_test)) # [ 5.  7. 0. 0. 0. 0. 0. 0. 0.]
print(hvad_kan_vaere_her(8,3,sudoku_fast_test)) # [ 5.  6.  8.  9. 0 ....]
print(hvad_kan_vaere_her(1,0,sudoku_fast_test)) # [ 0 0 0 0 ...]


In [ ]:
# skab mulighed rummet
def skab_muligheder(sudoku_fast):

    sudoku_muligheder = np.zeros([9,9,9])

    # Alle fast tal skal have 0, alle tom kasse skal have alle muligheder
    for i in np.arange(0,9):
        for j in np.arange(0,9):
            sudoku_muligheder[i,j,:] = hvad_kan_vaere_her(i,j,sudoku_fast)
            
    return sudoku_muligheder        
                
# Tester
sudoku_fast_test = sudoku_1
sudoku_muligheder_test = skab_muligheder(sudoku_fast_test)
print(sudoku_muligheder_test[0,0,:]) # [ 5.  7. 0. 0. 0. 0. 0. 0. 0.]
print(sudoku_muligheder_test[0,1,:]) # [ 1.  5.  6.  7.  8. 0. 0. 0. 0.]
print(sudoku_muligheder_test[8,8,:]) # [ 1.  2.  4.  7. 0. 0. 0. 0. 0.]
print(np.sum(sudoku_muligheder_test.flatten()))


In [ ]:
def find_faa_muligheder_sted(sudoku_muligheder, f_true=False):
    m_min = 9
    ii = -1
    jj = -1
    for i in np.arange(0,9):
        for j in np.arange(0,9):
            # print("i={},j={}: {}".format(i,j,sudoku_muligheder[i,j,:]))
            tmp = np.sum(~np.isin(sudoku_muligheder[i,j,:], 0))
            if ( m_min > tmp and tmp > 0 ):
                m_min = tmp
                ii = i
                jj = j
                faa_muligheder = sudoku_muligheder[ii,jj,:m_min]
                if not f_true:
                    if (m_min == 2): 
                        return [ii,jj,faa_muligheder]
                
    return [ii,jj,faa_muligheder]

# Test
sudoku_fast_test = sudoku_1
sudoku_muligheder_test = skab_muligheder(sudoku_fast_test)
[i,j,faa_muligheder] = find_faa_muligheder_sted(sudoku_muligheder_test)
print("i={},j={}: {}".format(i,j,faa_muligheder)) # i=0,j=0: [5. 7.]

In [ ]:
def fjern_muligheder(k,i,j,sudoku_muligheder):

        # fjern k fra linje i, alle søjler j  
        for jj in np.arange(0,9):
            # fjern mulighed hvis den ikke kan være her
            tmp = sudoku_muligheder[i,jj,:]
            tmp = tmp[~np.isin(tmp, k)]
            tmp = np.append(tmp, np.zeros(9-tmp.size))
            sudoku_muligheder[i,jj,:] = tmp
            
        # fjern k fra sojle j, alle linjer i  
        for ii in np.arange(0,9):
            # fjern mulighed hvis den ikke kan være her
            tmp = sudoku_muligheder[ii,j,:]
            tmp = tmp[~np.isin(tmp, k)]
            tmp = np.append(tmp, np.zeros(9-tmp.size))
            sudoku_muligheder[ii,j,:] = tmp
        
        # fjern k fra kvadrat  
        ii = int(np.floor(i/3)*3)
        jj = int(np.floor(j/3)*3)
        for iii in np.arange(ii,ii+3):
            for jjj in np.arange(jj,jj+3):
                tmp = sudoku_muligheder[iii,jjj,:]
                tmp = tmp[~np.isin(tmp, k)]
                tmp = np.append(tmp, np.zeros(9-tmp.size))
                sudoku_muligheder[iii,jjj,:] = tmp
                
        return sudoku_muligheder
    
# Tester (lidt blind ... testet ikke helt godt)
# Kan testes ved at tjekke muligheder efter A1 og A2 ( ToDo ) 


In [ ]:
# sudoku blocked
def is_sudoku_blocked(sudoku_fixed, sudoku_possibilities):
    for i in np.arange(0,9):
        for j in np.arange(0,9):
            if (sudoku_fixed[i,j]==0) and (np.sum(sudoku_possibilities[i,j,:])==0):
                print("Possibilities at [", i , "," , j , "] are: ", sudoku_possibilities[i,j,:])
                return 1
    return 0

# Tester
sudoku_fast_test = sudoku_1
sudoku_muligheder_test = skab_muligheder(sudoku_fast_test)
print(is_sudoku_blocked(sudoku_fast_test, sudoku_muligheder_test))
sudoku_muligheder_test[5,2,:]=np.array([0,0,0,0,0,0,0,0,0])
print(is_sudoku_blocked(sudoku_fast_test, sudoku_muligheder_test))

In [ ]:
# is Sudoku finished ?
def is_sudoku_finished(sudoku_fast):
    return ( np.sum(np.isin(sudoku_fast, 0)) == 0 ) 

# Tester
sudoku_fast_test = sudoku_1
print(is_sudoku_finished(sudoku_fast_test))

In [ ]:
# find steder med kun en mulighed 
def method_sub_A(sudoku_fast,sudoku_muligheder,op=2):

    method_sub_A_success = 0
    
    for i in np.arange(0,9):
        for j in np.arange(0,9):
   
            # Er kassen tom og findes der kun en mulighed ? Yubii !
            if ((sudoku_fast[i,j] == 0) and (sudoku_muligheder[i,j,0] != 0) and 
                   (sudoku_muligheder[i,j,1] == 0)):
                
                method_sub_A_success = 1
                
                sudoku_fast[i,j] = sudoku_muligheder[i,j,0]

                if (op == 1):
                    # OPTION 1: Regn alle muligheder igen 
                    sudoku_muligheder = skab_muligheder(sudoku_fast)
                    
                else:
                    # OPTION 2: Fjern controlleret mulighederne 
                    sudoku_muligheder[i,j,0] = 0
                    sudoku_muligheder = fjern_muligheder(sudoku_fast[i,j],i,j,sudoku_muligheder)
    
                # når vi printer giver vi indek fra 1 til 9 
                print("Fundet cife {} i position i={} j={}".format(sudoku_fast[i,j],i+1,j+1))
              
    return [ method_sub_A_success, sudoku_fast, sudoku_muligheder ]              

In [ ]:
# kør methode_sub_A så langt så muligt
# til at skrive den bedre
def method_A(sudoku_fast,sudoku_muligheder):
    
    sudoku_klar = 0
  
    while True: # do while method_sub_A_success == 1
        if (is_sudoku_blocked(sudoku_fast,sudoku_muligheder) ):
            print("Methode A: Sudoku blokeret")
            sudoku_klar = -1
            break
        if (is_sudoku_finished(sudoku_fast)):
            sudoku_klar = 1
            print("Methode A: Sudoku færdig")
            break
        [ method_sub_A_success, sudoku_fast, sudoku_muligheder ] = method_sub_A(sudoku_fast, sudoku_muligheder, 2)
        if (method_sub_A_success == 0 ):
            print("Methode A: kan ikke finde mere")
            sudoku_klar = 0
            break
        print("Methode A: Køre igen")

    return [ sudoku_klar, sudoku_fast, sudoku_muligheder ]   

In [ ]:
# start med steder med kun få muligheder
# valg en af dem tilfældig og metode A intil enten
# - metode A er færdige igen:
# a) tjek hvis metode A gav resultaten - return good
# b) den er sudokuen blokeret - return og valg ny mukighed
# c) eller sudokuen er ikke færdige - valg ny mulighed 

def method_B(sudoku_fast,sudoku_muligheder):
    
    # begynd med A
    [sudoku_klar, sudoku_fast, sudoku_muligheder] = method_A(sudoku_fast,sudoku_muligheder)
    
    if ( sudoku_klar == 1 ):
        print("Sudoku has solution:")
        print(sudoku_fast)
        return [sudoku_klar, sudoku_fast, sudoku_muligheder]
            
    elif ( sudoku_klar == 0 ): # kan ikke finde mere med methode A
        
        # valg en sted med få muligheder
        [ii,jj,faa_muligheder] = find_faa_muligheder_sted(sudoku_muligheder)
       
        for k in faa_muligheder:
            
            sudoku_fast_new = np.copy(sudoku_fast)
            sudoku_muligheder_new = np.copy(sudoku_muligheder)
            sudoku_fast_new[ii,jj] = k
            
            # når vi printer giver vi indek fra 1 til 9 
            print("Metode B: VALGT cife {} i position i={} j={} fra muligheder {}".format(k,ii+1,jj+1,faa_muligheder))
                
            # Fjern controlleret mulighederne tilsvarende til valget 
            sudoku_muligheder_new[ii,jj,:] = 0
            sudoku_muligheder_new = fjern_muligheder(k,ii,jj,sudoku_muligheder_new)
            
            # Prøve at løse den igen ...
            [ sudoku_klar, sudoku_fast_new, sudoku_muligheder_new ] = method_B(sudoku_fast_new,sudoku_muligheder_new)

            if (sudoku_klar == 1):
                sudoku_fast = sudoku_fast_new
                break

    return [sudoku_klar, sudoku_fast, sudoku_muligheder]

In [ ]:
# MAIN ALGORITHME 

sudoku_fast = np.copy(sudoku_7)
print(sudoku_fast)

# for alle tom kasse, finde mulighederene
sudoku_muligheder = skab_muligheder(sudoku_fast)

[ii,jj,faa_muligheder] = find_faa_muligheder_sted(sudoku_muligheder, True)
print("Estimated difficulty of Initial Sudoku by the fewest possibilities of an empty cell:\t", len(faa_muligheder))

[ sudoku_klar, sudoku_fast, sudoku_muligheder ] = method_B(sudoku_fast,sudoku_muligheder)
if (sudoku_klar !=1):
    print("Something is wrong with the sudoku input, could not solve it!")                       

In [ ]:
print("Finished Sudoku:\n", sudoku_fast)